name: build and push dockerfiles
on: 
  workflow_dispatch: 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker image A
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/api-service/Dockerfile
          push: true
          tags: |
            lendy1/api-service:latest
            lendy1/api-service:v1
      
      - name: Build and push Docker image B
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/info-service/Dockerfile
          push: true
          tags: lendy1/info-service:latest

      - name: Build and push Docker image C
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/login-service/Dockerfile
          push: true
          tags: lendy1/login-service:latest
      
      - name: Build and push Docker image D
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/root-service/Dockerfile
          push: true
          tags: lendy1/root-service:latest

      - name: Job status
        run: echo "This job's status is ${{ job.status }}."